var nome = ("ninja");
var xp = 10000
if (xp <=1000){
    var ranking = ("Ferro")
}else if(xp <=2000){
    var rankinga = ("bronze")
}else if(xp <=5000){
    var ranking = ("Prata")
}else if(xp <=7000){
    var ranking = ("Ouro")
}else if(xp <=8000){
    var ranking = ("Platina")
}else if(xp <=9000){
    var ranking = ("Ascendente")
}else if(xp <=10000){
    var ranking = ("Imortal")
}else if (xp >= 10001){
    var ranking = ("Radiante")
}
console.log ("O heroi " +  nome + " está no nivel de " +  ranking)


    
